name: fbreader
base: core20
version: '2.0.4'
summary: Your Favourite Book Reader
description: "Favourite Book Reader works on computers with all major operating systems (Linux, MacOSX, Windows) and mobile devices (iOS, Android). The FBReader features are

1) Comfortable reading. Customisable text styles and colours for day and night modes, advanced navigation features, and bookmarks.
2) Configurable network book sources list, from which you can download books for free and for a fee. You also can open your local books or add your preferred OPDS catalogues. FBReader provides a powerful catalogues browser, with browsing history, bookmarks, and search.
3) Transparent cloud integration. FBReader synchronises your books, reading positions and bookmarks across all your devices. Start reading a book on your computer, then continue from the same place on a tablet or smartphone.

Major book formats are ePub (including main features of ePub3), unencrypted Kindle azw3 (a.k.a. Mobipocket) and fb2(.zip). Other supported formats: RTF, doc (MS Word), HTML, and plain text."

license: Proprietary
icon: snap/gui/icon.png

plugs:
  fbreader-config:
    interface: personal-files
    write:
    - $HOME/.local/share/FBReader.ORG Limited
    - $HOME/.config/FBReader.ORG Limited

apps:
  fbreader:
    command: bin/FBReader
    command-chain:
    - bin/envelope.sh
    plugs:
    - desktop
    - desktop-legacy
    - network
    - network-bind
    - home
    - fbreader-config
    - removable-media
    - x11
    extensions:
    - gnome-3-38

grade: stable
confinement: strict

parts:
  qt6:
    source-type: local
    source: /root/project/Qt/6.5.2/gcc_64
    override-pull:
      mkdir -p lib/x86_64-linux-gnu;
      mkdir -p plugins/iconengines;
      mkdir -p plugins/imageformats;
      mkdir -p plugins/networkinformation;
      mkdir -p plugins/platforminputcontexts;
      mkdir -p plugins/platforms;
      mkdir -p plugins/platformthemes;
      mkdir -p plugins/tls;
      mkdir -p plugins/wayland-shell-integration;
      mkdir -p plugins/wayland-decoration-client;
      mkdir -p plugins/wayland-graphics-integration-client;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libicudata.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libicui18n.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libicuuc.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6Core.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6Core5Compat.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6DBus.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6Gui.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6Network.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6OpenGL.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6Pdf.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6Svg.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6WaylandClient.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6WaylandEglClientHwIntegration.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6WlShellIntegration.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6Widgets.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/lib/libQt6XcbQpa.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.5.2/gcc_64/plugins/iconengines/libqsvgicon.so plugins/iconengines;
      cp /root/project/Qt/6.5.2/gcc_64/plugins/imageformats/*.so plugins/imageformats;
      cp /root/project/Qt/6.5.2/gcc_64/plugins/networkinformation/*.so plugins/networkinformation;
      cp /root/project/Qt/6.5.2/gcc_64/plugins/platforminputcontexts/*.so plugins/platforminputcontexts;
      cp /root/project/Qt/6.5.2/gcc_64/plugins/platforms/*.so plugins/platforms;
      cp /root/project/Qt/6.5.2/gcc_64/plugins/platformthemes/*.so plugins/platformthemes;
      cp /root/project/Qt/6.5.2/gcc_64/plugins/tls/*.so plugins/tls;
      cp /root/project/Qt/6.5.2/gcc_64/plugins/wayland-shell-integration/*.so plugins/wayland-shell-integration;
      cp /root/project/Qt/6.5.2/gcc_64/plugins/wayland-decoration-client/*.so plugins/wayland-decoration-client;
      cp /root/project/Qt/6.5.2/gcc_64/plugins/wayland-graphics-integration-client/*.so plugins/wayland-graphics-integration-client;
      mkdir -p lib/x86_64-linux-gnu/engines;
      mkdir -p lib/x86_64-linux-gnu/providers;
      cp /root/project/src/openssl/openssl-3.0.8/engines/*.so lib/x86_64-linux-gnu/engines;
      cp /root/project/src/openssl/openssl-3.0.8/providers/*.so lib/x86_64-linux-gnu/providers;
      cp /root/project/src/openssl/openssl-3.0.8/*.so lib/x86_64-linux-gnu;
      cp /root/project/src/openssl/openssl-3.0.8/*.so.3 lib/x86_64-linux-gnu;
    organize:
      '*': usr/
    plugin: dump
    stage:
    - usr/*
    filesets:
      exclude-unused:
      - -usr/lib/cmake
    prime:
    - $exclude-unused

  app:
    after:
    - qt6
    source: /root/project/src
    source-type: local
    plugin: cmake
    cmake-parameters:
    - -DCMAKE_TOOLCHAIN_FILE=/root/project/Qt/6.5.2/gcc_64/lib/cmake/Qt6/qt.toolchain.cmake
    - -DCMAKE_INSTALL_PREFIX=/
    - -DPACKAGE_TYPE=snap
    build-packages:
    - libgl-dev
    - libegl-dev
    - libfontconfig1-dev
    - libxkbcommon-dev
    - rapidjson-dev
    - libsqlite3-dev
    - libunibreak-dev
    - libicu-dev
    - libbz2-dev
    - liblzma-dev
    - ccache
    - git
    stage-packages:
    - libgl1
    - libegl1
    - libfontconfig1
    - libfreetype6
    - libpng16-16
    - libx11-6
    - libxau6
    - libxcb1
    - libxdmcp6
    - libxkbcommon0
    - libxkbcommon-x11-0
    - libxcb-cursor0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-render0
    - libxcb-shape0
    - libsqlite3-0
    - libunibreak1
    - libicu66
    - libffi7
    - libbz2-1.0
    - liblzma5
