name: fbreader
base: core20
version: '2.0beta1'

plugs:
  write-downloads:
    interface: personal-files
    write:
      - $HOME/Downloads

apps:
  fbreader:
    command: bin/FBReader
    plugs:
      - desktop
      - desktop-legacy
      - network
      - network-bind
      - write-downloads
      - home
    environment:
      HOME: $SNAP_REAL_HOME

summary: An ebook reader
description: |
  An ebook reader.
icon: snap/gui/icon.png

grade: devel
confinement: devmode

parts:
  qt6:
    source-type: local
    source: /root/project/Qt/6.2.1/gcc_64
    override-pull:
      mkdir -p lib/x86_64-linux-gnu;
      mkdir -p plugins/iconengines;
      mkdir -p plugins/imageformats;
      mkdir -p plugins/platforms;
      mkdir -p plugins/tls;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libicudata.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libicui18n.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libicuuc.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libQt6Core.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libQt6Core5Compat.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libQt6DBus.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libQt6Gui.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libQt6Network.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libQt6OpenGL.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libQt6Svg.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libQt6Widgets.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/lib/libQt6XcbQpa.so.* lib/x86_64-linux-gnu;
      cp /root/project/Qt/6.2.1/gcc_64/plugins/iconengines/libqsvgicon.so plugins/iconengines;
      cp /root/project/Qt/6.2.1/gcc_64/plugins/imageformats/*.so plugins/imageformats;
      cp /root/project/Qt/6.2.1/gcc_64/plugins/platforms/libqxcb.so plugins/platforms;
      cp /root/project/Qt/6.2.1/gcc_64/plugins/tls/*.so plugins/tls;
    organize:
      '*': usr/
    plugin: dump
    stage:
      - usr/*

  ziplib:
    source: /root/project/ziplib
    source-type: local
    plugin: make

  app:
    after:
      - ziplib
    source: /root/project/src
    source-type: local
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_TOOLCHAIN_FILE=/root/project/Qt/6.2.1/gcc_64/lib/cmake/Qt6/qt.toolchain.cmake
      - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
      - libgl-dev
      - libegl-dev
      - libfontconfig1-dev
      - libxkbcommon-dev
      - rapidjson-dev
      - libsqlite3-dev
      - libunibreak-dev
      - ccache
    stage-packages:
      - libgl1
      - libegl1
      - libfontconfig1
      - libfreetype6
      - libpng16-16
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-render0
      - libxcb-shape0
      - libsqlite3-0
      - libunibreak1
